//! SDK projection for the Claude harness.
//!
//! The CLI backend is the primary execution target; SDK backends are
//! secondary and often lossy. This module turns a resolved roster into
//! an artifact the operator can drop into a TypeScript or Python Claude
//! Agent SDK project — typically a config fragment or a runner script
//! that configures the SDK with equivalent settings.
//!
//! We deliberately emit code the user should review rather than
//! auto-executing an SDK run: the projection is advisory, designed to
//! show the user what their CLI roster maps onto in SDK land plus any
//! warnings (via [`crate::resolve::ResolvedClaudeRoster::projection_diagnostics`])
//! about behavior that doesn't faithfully round-trip.

use katachi_core::diagnostic::Diagnostic;
use katachi_core::model::BackendKind;

use crate::resolve::ResolvedClaudeRoster;

/// A projection of a Claude roster to an SDK-friendly shape.
#[derive(Clone, Debug)]
pub struct SdkProjection {
    pub backend: BackendKind,
    /// Source code the user can paste into an SDK runner.
    pub code: String,
    /// Warnings specific to this projection.
    pub diagnostics: Vec<Diagnostic>,
}

/// Build an SDK projection for the given backend. Returns
/// [`SdkProjection`] regardless of loss; callers render the
/// diagnostics so operators know what they're giving up.
pub fn project(
    resolved: &ResolvedClaudeRoster,
    backend: BackendKind,
) -> SdkProjection {
    match backend {
        BackendKind::SdkTs => project_ts(resolved),
        BackendKind::SdkPy => project_py(resolved),
        other => SdkProjection {
            backend: other,
            code: format!("// SDK projection for backend `{other}` is not available yet.\n"),
            diagnostics: vec![Diagnostic::error(
                "claude.sdk-unsupported-backend",
                format!("backend `{other}` is not a Claude SDK target"),
            )],
        },
    }
}

fn project_ts(resolved: &ResolvedClaudeRoster) -> SdkProjection {
    let profile = &resolved.roster.run_profile;
    let mut code = String::new();
    code.push_str("// Generated by katachi harness claude project --sdk-ts\n");
    code.push_str("// Review before running — SDK projection is advisory.\n\n");
    code.push_str("import { query } from \"@anthropic-ai/claude-agent-sdk\";\n\n");
    code.push_str("async function run(prompt: string) {\n");
    code.push_str("  for await (const event of query({\n");
    code.push_str("    prompt,\n");
    if let Some(model) = &profile.model {
        code.push_str(&format!("    model: {:?},\n", model));
    }
    if let Some(sys) = &profile.append_system_prompt {
        code.push_str(&format!(
            "    systemPrompt: {{ preset: \"claude_code\", append: {:?} }},\n",
            sys
        ));
    } else if let Some(sys) = &profile.system_prompt {
        code.push_str(&format!("    systemPrompt: {:?},\n", sys));
    }
    if let Some(perm) = &profile.permission_mode {
        code.push_str(&format!("    permissionMode: {:?},\n", perm));
    }
    if !profile.setting_sources.is_empty() {
        let ss: Vec<String> = profile
            .setting_sources
            .iter()
            .map(|s| format!("{:?}", s))
            .collect();
        code.push_str(&format!("    settingSources: [{}],\n", ss.join(", ")));
    }
    if !profile.allowed_tools.is_empty() {
        let t: Vec<String> = profile.allowed_tools.iter().map(|t| format!("{:?}", t)).collect();
        code.push_str(&format!("    allowedTools: [{}],\n", t.join(", ")));
    }
    if !profile.disallowed_tools.is_empty() {
        let t: Vec<String> = profile
            .disallowed_tools
            .iter()
            .map(|t| format!("{:?}", t))
            .collect();
        code.push_str(&format!("    disallowedTools: [{}],\n", t.join(", ")));
    }
    if let Some(max_turns) = profile.max_turns {
        code.push_str(&format!("    maxTurns: {},\n", max_turns));
    }
    code.push_str("  })) {\n");
    code.push_str("    console.log(JSON.stringify(event));\n");
    code.push_str("  }\n");
    code.push_str("}\n\n");
    code.push_str("run(process.argv.slice(2).join(\" \") || \"\").catch(err => {\n");
    code.push_str("  console.error(err);\n  process.exit(1);\n});\n");

    let mut diagnostics = resolved.projection_diagnostics.clone();
    diagnostics.extend(selected_item_warnings(resolved));
    SdkProjection {
        backend: BackendKind::SdkTs,
        code,
        diagnostics,
    }
}

fn project_py(resolved: &ResolvedClaudeRoster) -> SdkProjection {
    let profile = &resolved.roster.run_profile;
    let mut code = String::new();
    code.push_str("# Generated by katachi harness claude project --sdk-py\n");
    code.push_str("# Review before running — SDK projection is advisory.\n\n");
    code.push_str("import asyncio\n");
    code.push_str("from claude_agent_sdk import query, ClaudeAgentOptions\n\n");
    code.push_str("async def run(prompt: str):\n");
    code.push_str("    options = ClaudeAgentOptions(\n");
    if let Some(model) = &profile.model {
        code.push_str(&format!("        model={:?},\n", model));
    }
    if let Some(sys) = &profile.append_system_prompt {
        code.push_str(&format!(
            "        system_prompt={{\"preset\": \"claude_code\", \"append\": {:?}}},\n",
            sys
        ));
    } else if let Some(sys) = &profile.system_prompt {
        code.push_str(&format!("        system_prompt={:?},\n", sys));
    }
    if let Some(perm) = &profile.permission_mode {
        code.push_str(&format!("        permission_mode={:?},\n", perm));
    }
    if !profile.setting_sources.is_empty() {
        let ss: Vec<String> = profile
            .setting_sources
            .iter()
            .map(|s| format!("{:?}", s))
            .collect();
        code.push_str(&format!("        setting_sources=[{}],\n", ss.join(", ")));
    }
    if !profile.allowed_tools.is_empty() {
        let t: Vec<String> = profile.allowed_tools.iter().map(|t| format!("{:?}", t)).collect();
        code.push_str(&format!("        allowed_tools=[{}],\n", t.join(", ")));
    }
    if !profile.disallowed_tools.is_empty() {
        let t: Vec<String> = profile
            .disallowed_tools
            .iter()
            .map(|t| format!("{:?}", t))
            .collect();
        code.push_str(&format!(
            "        disallowed_tools=[{}],\n",
            t.join(", ")
        ));
    }
    if let Some(max_turns) = profile.max_turns {
        code.push_str(&format!("        max_turns={},\n", max_turns));
    }
    code.push_str("    )\n");
    code.push_str("    async for event in query(prompt=prompt, options=options):\n");
    code.push_str("        print(event)\n\n");
    code.push_str("if __name__ == \"__main__\":\n");
    code.push_str("    import sys\n");
    code.push_str("    asyncio.run(run(\" \".join(sys.argv[1:])))\n");

    let mut diagnostics = resolved.projection_diagnostics.clone();
    diagnostics.extend(selected_item_warnings(resolved));
    SdkProjection {
        backend: BackendKind::SdkPy,
        code,
        diagnostics,
    }
}

fn selected_item_warnings(resolved: &ResolvedClaudeRoster) -> Vec<Diagnostic> {
    let mut out = Vec::new();
    for r in &resolved.resolved.selected_items {
        let Some(item) = resolved.catalog.get(&r.item) else {
            continue;
        };
        match item.item_ref.kind.as_str() {
            "plugin" => {
                out.push(Diagnostic::warning(
                    "claude.sdk-projection-plugin",
                    format!(
                        "plugin `{}` needs to be installed alongside the SDK project manually",
                        r.item
                    ),
                ));
            }
            "hook_set" => {
                out.push(Diagnostic::warning(
                    "claude.sdk-projection-hook",
                    format!(
                        "hook `{}` needs to be wired as an SDK callback — settings-layer configs don't carry across",
                        r.item
                    ),
                ));
            }
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::resolve::resolve_roster;
    use crate::roster::ClaudeRoster;
    use camino::Utf8PathBuf;
    use katachi_core::harness::{DiscoveredItem, ItemSource, RosterCatalog};
    use katachi_core::model::{BackendKind, HarnessKind, ItemRef};

    fn build_resolved(selected_plugin: Option<&str>) -> ResolvedClaudeRoster {
        let mut cat = RosterCatalog::empty(HarnessKind::Claude);
        if let Some(pid) = selected_plugin {
            cat.insert_item(DiscoveredItem {
                item_ref: ItemRef::new(HarnessKind::Claude, "plugin", pid),
                display_name: pid.into(),
                source: ItemSource::default(),
                packaging: None,
                raw: serde_json::Value::Null,
                capabilities: Vec::new(),
                constraints: Vec::new(),
            })
            .unwrap();
        }
        let toml = format!(
            r#"
version = 1
id = "r"
[selection]
plugins = [{}]
[run_profile]
model = "sonnet"
permission_mode = "plan"
setting_sources = ["project"]
allowed_tools = ["Bash"]
append_system_prompt = "be helpful"
max_turns = 5
"#,
            selected_plugin
                .map(|p| format!("\"{p}\""))
                .unwrap_or_default()
        );
        let roster =
            ClaudeRoster::from_toml_str(&Utf8PathBuf::from("t.toml"), &toml).unwrap();
        resolve_roster(&roster, cat, BackendKind::Cli)
    }

    #[test]
    fn ts_projection_includes_model_and_tools() {
        let resolved = build_resolved(None);
        let p = project(&resolved, BackendKind::SdkTs);
        assert!(p.code.contains("model: \"sonnet\""));
        assert!(p.code.contains("allowedTools: [\"Bash\"]"));
        assert!(p.code.contains("permissionMode: \"plan\""));
        assert!(p.code.contains("maxTurns: 5"));
    }

    #[test]
    fn py_projection_includes_system_prompt_append() {
        let resolved = build_resolved(None);
        let p = project(&resolved, BackendKind::SdkPy);
        assert!(p.code.contains("model=\"sonnet\""));
        assert!(p.code.contains("allowed_tools=[\"Bash\"]"));
        assert!(p
            .code
            .contains(r#"system_prompt={"preset": "claude_code", "append": "be helpful"}"#));
    }

    #[test]
    fn plugin_selection_emits_projection_warning() {
        let resolved = build_resolved(Some("web-a11y"));
        let p = project(&resolved, BackendKind::SdkTs);
        assert!(p
            .diagnostics
            .iter()
            .any(|d| d.code == "claude.sdk-projection-plugin"));
    }

    #[test]
    fn unsupported_backend_emits_error() {
        let resolved = build_resolved(None);
        let p = project(&resolved, BackendKind::McpServer);
        assert!(p
            .diagnostics
            .iter()
            .any(|d| d.code == "claude.sdk-unsupported-backend"));
    }
}
